import sys
from enum import Enum


class constants(str, Enum):
    WELOVEBOT_CONFIG_PREFIX_DEFAULT = 'WELOVEBOT'
    WELOVEBOT_CONFIG_PREFIX_ENVVAR = 'WELOVEBOT_CONFIG_PREFIX'
    WELOVEBOT_APPS_DEFAULT = 'welovebot.apps'
    WELOVEBOT_APPS_ENVVAR = 'WELOVEBOT_APPS'
